# Generated by Django 5.1.6 on 2025-03-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
