# Generated by Django 5.1.6 on 2025-03-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_category_options_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='articles.article'),
        ),
    ]
